### ISSUE TITLE
Remove form-field folder

### ISSUE THREAD

**Issue by Kingcedru** [d-rec/drec-ui#153]
Subticket of https://github.com/d-rec/drec-ui/issues/150

**Objective:**
- To remove the form-field folder from the project.

**Description:**
- The form-field folder is not being used in the project and we won't use it in the future so it needs to be removed.

**Acceptance Criteria:**
- The form-field folder is removed from the project.
- Run tests and check if everything works well
  - The UI project runs without any issue (doesn't cause any regression error)

**Comment by divinecharlotte** [comment]
Hey @Kingcedru this is a subticket 150, not 149 😃 kindly check it out and fix this.
