### ISSUE TITLE
Remove getNamesFromCode file

### ISSUE THREAD

**Issue by Kingcedru** [d-rec/drec-ui#155]
Subticket of https://github.com/d-rec/drec-ui/issues/150

**Objective:**
- To remove the getNamesFromCode file from the project.

**Description:**
- The getNamesFromCode file is empty and it doesn't have an use and we also don't need it in the future.

**Acceptance Criteria:**
- The getNamesFromCode file is removed from the project.
- Run tests and check if everything works well
  - The UI project runs without any issue (doesn't cause any regression error)

**Comment by divinecharlotte** [comment]
Hey @Kingcedru this is a subticket 150, not 149 😃 kindly check it out and fix this.
