### ISSUE TITLE
Update The DREC logo to use the one without the "Initiative"

### ISSUE THREAD

**Issue by Kingcedru** [d-rec/drec-ui#180]
**Objective:**
- Update the D-REC logo and use the one without the "Initiative text".

**Description:**
- Update all D-REC logos.

**Acceptance Criteria:**
- All D-REC logo are updated with the one without the  "Initiative text".
- Run tests and check if everything works well.
  - The UI project runs without any issue (doesn't cause any regression error)

**Comment by musayann** [comment]
![Image](https://github.com/user-attachments/assets/844f9995-5da2-4e09-b3e0-359a239e99f2)
![Image](https://github.com/user-attachments/assets/98d67041-e9bc-49c1-ab99-c4ef8f9483f9)
