### ISSUE TITLE
D-REC Test Cases Document

### ISSUE THREAD

**Issue by rithaven** [d-rec/drec-ui#182]
### Objective:
Test and document test cases for all relevant functionalities in the D-REC project, ensuring each feature is fully tested and validated.

### Description:
This ticket tracks the progress of the D-REC project's test cases documentation. Each related test case will be documented in its respective sub-ticket, focusing on the functionality requirements and expected outcomes.

### Acceptance Criteria:

 - All necessary test cases are documented and categorized under their respective sub-tickets.
 - Each test case document is thorough, covering all relevant functionalities and edge cases.
 - Links to all test case documents are organized within this ticket for easy access and updates.

### Next Steps:
The document will be continuously updated as the project progresses. Each major set of test cases will have its sub-ticket linked to this parent ticket.

### Design::

[[Link to the Test Cases folder]](https://drive.google.com/drive/folders/1ZWlm0nkhrDEy8Uk3o45O7m6AoThLuU9e?usp=drive_link)

**Comment by musayann** [comment]
@rithaven Create subtickets for this ticket which includes any test case that you are working on. Each set of test case ( A document) should have a ticket which is related to it. Follow this template https://github.com/d-rec/drec-ui/wiki/Ticket-template
